### ISSUE TITLE
wiki page requires password

### ISSUE THREAD

**Issue by techtonik** [sergeyvfx/fm#1]
Just wanted to see some screens and got auth form instead for http://nazg-gul.dyndns.org/wiki/

**Comment by sergeyvfx** [comment]
The project is pretty much stagnated since 2010 and no development happened since then. It's not that much of an use currently and maintaining wiki to keep spam away became too much of a hassle, so it is now disabled.

It shouldn't be hard to compile project and run it yourself to get screenshots tho.

**Comment by techtonik** [comment]
Should it be migrated to GitHub instead?

**Comment by sergeyvfx** [comment]
Don't see any reason for that unless someone picks up the code development.

**Comment by techtonik** [comment]
I can't pick up code for something that I haven't even seen, so I need to screenshots at least.

Then there is a licensing problem - GPL code is cool, but it is kind of hard to make living applying GPL codebase in paid development.
